const config = {
  SYMBOL_API_ENDPOINT: process.env.REACT_APP_SYMBOL_API_ENDPOINT,
  GENERATION_HASH_SEED: process.env.REACT_APP_GENERATION_HASH_SEED,
  FEE_MULTIPLIER: process.env.REACT_APP_FEE_MULTIPLIER,
  EPOCH_ADJUSTMENT: process.env.REACT_APP_EPOCH_ADJUSTMENT,
  NETWORK_TYPE: process.env.REACT_APP_NETWORK_TYPE,
}

export default config
